myList = ["apple", "banana", "cherry"]
print(myList [1])
print(myList)

tuple = ("111", "222", "333","1","2","4","1221")

print(tuple[2])
print(tuple[0])
print(tuple[0:4])
print(tuple[0:])
print(tuple[-1])
print(tuple[-4])
print(tuple[:-1])
print(tuple[-1:])
print(tuple[-5:])
#hw using index + slice print different elements

print(tuple[2:6])
print(tuple[:5])
print(tuple[3:])
print(tuple[::2])
print(tuple[::-1])
print(tuple[5])